package com.uady.blackWolfCinema.model;

import java.time.LocalDate;
import java.time.LocalTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

@Entity
@Table(name= "movie_show")
public class Show {

    //Primary key for the show entity (showId), is auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idshow")
    private int showId;

    @Column(name="date")
    @NotNull(message = "Este campo no puede ir vacio")
    private LocalDate showDate;

    @Column(name="hour")
    @NotNull(message = "Esta campo no puede ir vacio")
    private LocalTime showHour;

    @ManyToOne
    @JoinColumn(name = "idmovie", referencedColumnName = "idmovie")
    private Movie movie;

    @ManyToOne
    @JoinColumn(name = "idcinema_room", referencedColumnName = "idcinema_room")
    private CinemaRoom cinemaRoom;

    public Show(){

    }

    public Show(LocalDate showDate, LocalTime showHour, Movie movie, CinemaRoom cinemaRoom) {
        this.showDate = showDate;
        this.showHour = showHour;
        this.movie=movie;
        this.cinemaRoom=cinemaRoom;
    }

    public int getShowId() {
        return showId;
    }

    public void setShowId(int showId) {
        this.showId = showId;
    }

    public LocalDate getShowDate() {
        return showDate;
    }

    public void setShowDate(LocalDate showDate) {
        this.showDate = showDate;
    }

    public LocalTime getShowHour() {
        return showHour;
    }

    public void setShowHour(LocalTime showHour) {
        this.showHour = showHour;
    }

    public Movie getMovie() {
        return movie;
    }

    public void setMovie(Movie movie) {
        this.movie = movie;
    }

    public CinemaRoom getCinemaRoom() {
        return cinemaRoom;
    }

    public void setCinemaRoom(CinemaRoom cinemaRoom) {
        this.cinemaRoom = cinemaRoom;
    }
}

